warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java
Added command line option with unchanged default behaviour (commit before each (W)ARC file as well af after all (W)ARC files).
=> Fixes #42 (Explicit client commits should be optional)

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/ImageAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/PDFAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/XMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/text/FuzzyHashAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/text/LanguageAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/text/PostcodeAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/text/TextAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/extract/LanguageDetector.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java, warc-indexer/src/main/java/uk/bl/wa/util/Instrument.java, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/test/java/uk/bl/wa/solr/TikaExtractorTest.java, warc-indexer/src/test/java/uk/bl/wa/util/InstrumentTest.java
This pull is primarily about performance instrumentation: The class Instrument was added for lightweight tracking of where the time is spend (sample output below). The final report is currently only triggered by the `WARCIndexerCommand` with `Instrument.log(true)`.
Eye opener: Detecting language on our (admittedly tiny) sample took 1/5th of the total time.
```
WARC Indexer Finished in 180.572 seconds.
2015-02-12 15:43:12 INFO  Instrument:166 - Performance statistics
SolrRecord.removeControlCharacters#total(#=253778, time=3003.60ms, avg=84.49#/ms 0.01ms/#)
SolrRecord.sanitiseUTF8(#=253778, time=961.46ms, avg=263.95#/ms 0.00ms/#)
WARCIndexerCommand.main#total(#=1, time=180577.93ms, avg=0.00#/ms 180577.93ms/#)
WARCIndexerCommand.parseWarcFiles#startup(#=1, time=4681.03ms, avg=0.00#/ms …
```
=> Performance instrumentation

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java
If the query sanitizer removes all characters for the input String, the empty String is currently added to the Solr index. The empty-term noise is especially visible with sorting and faceting.
This patch adds a simple check and discards the field update if there are no content.
=> Empty terms should not be added

CHANGES.md, warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/outlinks/OutlinkExtractorMapper.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/extract/LinkExtractor.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/test/java/uk/bl/wa/analyser/payload/HTMLAnalyserTest.java, warc-indexer/src/test/resources/links_extract.conf, warc-indexer/src/test/resources/links_extract.html
Encoding lists of links as a single space-separated String introduces a performance penalty and results in errors when there are spaces in the links themselves. This patch switches to String[] as the transport mechanism. Unit test included.
=> Switched HTML links extraction from String join/split on space to String[]

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrFields.java, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/main/solr/solr/discovery/conf/schema.xml, warc-indexer/src/test/java/uk/bl/wa/parsers/HtmlFeatureParserTest.java
This patch optionally normalises links extracted from HTML as well as the URL from the WAR(C). The normaliser uses the AggressiveUrlCanonicalizer.
This patch does not convert to SURT format. This might be an idea for a future feature, but care must be taken not to mix this with standard host- and domain-links.
=> Optional link and URL normalisation

warc-indexer/src/main/java/uk/bl/wa/annotation/Annotations.java, warc-indexer/src/main/java/uk/bl/wa/annotation/Annotator.java, warc-indexer/src/test/java/uk/bl/wa/annotation/AnnotationsTest.java, warc-indexer/src/test/java/uk/bl/wa/annotation/AnnotatorTest.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerEmbeddedSolrTest.java, warc-indexer/src/test/resources/annotations/mona-lisa-annotations.json
A proposition for issue #88 
Now if you use the annotations mechanism, if the name of your warc file contains a source_file_prefix (from the annotation file), the corresponding informations will be add to the solr document.
=> Extend annotations mechanism to allow source file prefix as a scope

warc-indexer/src/main/java/uk/bl/wa/util/HashedCachedInputStream.java
The lengths of two hashes should be compared at first. It should solve the problem of different SHA algorithms as well.
=> Extend to cope with converted WARC records #111

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/ARCNameAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java, warc-indexer/src/main/java/uk/bl/wa/util/Instrument.java, warc-indexer/src/test/java/uk/bl/wa/util/InstrumentTest.java
Adds performance breakdown of which types (as stated by the server) of files takes the longest to process. Sample output from a `warc-indexer`-run:
```
WARCIndexer#content_types(#=0, time=0.00ms, avg=0.00#/ms 0.00ms/#, 0.00%)
WARCIndexer#content_type_served=text/html(#=1224, time=17780.81ms, avg=0.07#/ms 14.53ms/#, 53.09%)
WARCIndexer#content_type_served=application/x-javascript(#=1129, time=14219.61ms, avg=0.08#/ms 12.59ms/#, 42.46%)
WARCIndexer#content_type_served=image/jpeg(#=2, time=103.77ms, avg=0.02#/ms 51.88ms/#, 0.31%)
WARCIndexer#content_type_served=text/plain(#=1, time=22.95ms, avg=0.04#/ms 22.95ms/#, 0.07%)
```
=> Mine stats

warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java
Simple feature implementation, activated with `-z` in the command line tool. Tested manually by creating gzipped output and indexing it from the command line, as described in #123. This closes #123.
=> Implementation of issue #123 (Add gzipped XML file as output option)

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/ImageAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrFields.java, warc-indexer/src/main/java/uk/bl/wa/solr/TikaExtractor.java, warc-indexer/src/main/resources/log4j-override.properties, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/main/solr/solr/discovery/conf/schema.xml, warc-indexer/src/test/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysersTest.java, warc-indexer/src/test/resources/arcnameanalyser.conf, warc-indexer/src/test/resources/links_extract.conf
Hi Andy.
This is first off 2 pull requests from us. This one has a few new fields and minor changes. Read the changes about the links field. The next pull request will come in 2 weeks and will be enchancments to revisits records.
/Thomas Egense
New solr fields:
index_time . When the record was indexed. This is useful for researchers to define a corpus that does not change when more is indexed.
links_images. All images on an html page. 
warc_key_id  (from warc header)
warc_ip (from warc header)
arc_full (Only if defined in config.conf). Stores the absolute path of the warc. (for solrwayback)
exif_location (for images, only if enabled in config.con)
exif_version (for images, only if enabled in config.con)
links (already defined by you, but I have normalized the links to match them the same …
=> 3.0 enhancements

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/resources/reference.conf
Instead of giving the annotations file in the command line, there is now in the config file a setting to enable the annotations mechanism and define the annotations file path and the openAccessSurts file.
=> Move annotations call from CLI to config file (issue #113)

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/annotation/AnnotationsFromAct.java, warc-indexer/src/main/java/uk/bl/wa/annotation/Annotator.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/main/java/uk/bl/wa/solr/TikaExtractor.java, warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/test/java/uk/bl/wa/extract/LinkExtractorTest.java, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
Extraction of URL-normalisation to a single class and implementation of #115 and #119, so that `links` and `links_images` are now normalised unambiguously to `url_norm`. This should lift the quality of link matching.
=> URL-normalisation

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/test/java/uk/bl/wa/parsers/HtmlFeatureParserTest.java, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
Handles issues #136, #137, #138 & #139.
- #138 is handled by returning explicit escapes of invalid UTF-8 codepoints. If anyone feels for it, an "assume charset X if not UTF-8" option could be added.
- #136 is handled by adjusting the test. This could also be handled by removing all trailing slashes from domain-level links.
=> Url hardening

warc-indexer/src/main/solr/solr/discovery/conf/schema.xml, warc-indexer/src/main/solr/solr/discovery/conf/stopwords_path.txt
This closes #110 by adding a custom analyzer chain to `resourcename` and introducing the field `url_search`.
In order to search in the new `url_search`-field per default, `solrconfig.xml` should be changed to use the `edismax`-parser instead of the default single-field matching on `text`. I have opened #134.
=> Better search in url and resourcename

warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
A space and a plus are just that in the path-part of an URL, but for parameters space is normally converted to plus. This pull request normalises ` `, `%20` and `+` to `+` in the parameter-part of an URL.
Sample:
`http://example.com/%20 +path?foo=%20 +` (raw)
`http://example.com/%20%20+path?foo=+++` (normalised)
=> Space should be converted to plus if found in parameter part of URL

warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/test/java/uk/bl/wa/parsers/HtmlFeatureParserTest.java
At the Royal Danish Library we have a lot of garbage in the tags-list. This is because JSoup treats the content of `script`-elements as HTML: `<script> if (a<b) console.log('foo');</script>` will result in the tags `script` and `b)`.
This pull-request performs light-weight pruning by only accepting valid tags, i.e. tags that satisfies the regular expression `[a-zA-Z0-9]+`. This easy solution has at least two downsides:
1. It does not handle all cases (e.g. `<script> if ( a<b ) console.log('foo');</script>` will give the tage `script` and `b`, since there is a space after `<b` in the JavaScript)
1. Filters out invalid tags that might be interesting from a researcher perspective (e.g. `<vitæ>life</vitæ>`)
Handling the first case is complicated as it requires a tree-like parsing of HTML and …
=> Pruning of invalid tag names extracted by JSoup

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrFields.java, warc-indexer/src/main/solr/solr/discovery/conf/schema.xml
For http 3xx (redirect) documents the redirect to url is now indexed.
new scema.xml field:redirect_to_norm
So no change in indexing unless you index http 3XX status codes. (defined in the config.conf for the warc-indexer).
Has been tested in corpus and seems to work correct. The redirect url can be relative, so it had to be resolved compared to the current url.
The branch name should have been 'redirect' instead of referrer, so dont think to much about the branch name, sorry.
/Thomas
=> New field for redirect URL  HTTP 3xx codes

warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/indexer/WARCIndexerMapper.java, warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/indexer/WritableSolrRecord.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecordFactory.java, warc-indexer/src/main/java/uk/bl/wa/solr/WctEnricher.java, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/test/java/uk/bl/wa/analyser/payload/HTMLAnalyserTest.java, warc-indexer/src/test/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysersTest.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerTest.java, warc-indexer/src/test/java/uk/bl/wa/solr/SolrRecordFactoryTest.java, warc-indexer/src/test/java/uk/bl/wa/solr/TikaExtractorTest.java
We (at Royal Danish Library) are not comfortable with the full disabling the max Solr field length feature, especially not for things like `links` extraction. This pull request makes the max limits for fields configurable on a field-per-field basis. `reference.conf` has been updated with the following section, which should demonstrate how this works:
```
"field_setup" : {
"default_max_length" : -1,
"fields" : {
"url" :      { "max_length" : 2048 }, # de facto max length for GET URLs
"url_norm" : { "max_length" : 2048 },
"links" :    { "max_length" : 2048 },
"content" :  { "max_length" : 512K }, # Same as tika.max_text_length
},
},
```
The format layout has been chosen in anticipation of extension. One candidate could be to introduce a limit on the number of entries for the field, e.g. to …
=> Configurable field length limit

digipres-tika/src/main/java/uk/bl/wa/tika/parser/warc/WebARCExtractor.java, warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/entities/EntityMapper.java, warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/indexer/WARCIndexerMapper.java, warc-hadoop-indexer/src/main/java/uk/bl/wa/hadoop/outlinks/OutlinkExtractorMapper.java, warc-hadoop-indexer/src/test/java/uk/bl/wa/hadoop/indexer/mdx/WARCMDXMapperTest.java, warc-hadoop-recordreaders/src/main/java/uk/bl/wa/hadoop/mapreduce/warcstats/WARCRawStatsMapper.java, warc-hadoop-recordreaders/src/main/java/uk/bl/wa/hadoop/mapreduce/warcstats/WARCStatsMapper.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/HTMLAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/PDFAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/main/java/uk/bl/wa/solr/SolrRecord.java, warc-indexer/src/main/java/uk/bl/wa/util/HashedCachedInputStream.java, warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerEmbeddedSolrTest.java, warc-indexer/src/test/java/uk/bl/wa/parsers/HtmlFeatureParserTest.java, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
The OS-X Homebrew version of wget (and possibly all wget versions > 1.19.4) encapsulates WARC-header URLs in `<>`, which is not handled by the archive.org header-processing class used in `webarchive-discovery`. This pull request performs explicit check & removal of `<>`-encapsulation where `header.getUrl()` is used. The implementation should not have any adverse effects as absolute URLs are not allowed to start with `<`.
A better solution long term solution would be to upgrade the code from archive.org or re-implement that code elsewhere.
This closes #159
=> Handles WARC-header URLs encapsulated in <>

warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java
Fix for issue #165.
If the current corrupted record has the same recordCount, it's the same one, so it ends the indexer.
=> Fix infinite loop when the last record is corrupted

warc-indexer/src/main/solr/solr/discovery/conf/schema.xml
Non-critical tweaks to the old Solr 4/5 `schema.xml`.
This changes `stored` to `docValues` for some fields, enabling efficient sorting, grouping & faceting. Retrievability is not affected as Solr 4 is capable of returning `docValues` fields as if they were `stored` as long as they are not `multiValued`.
Also sets `resourcename_facet` to `indexed` as that is needed for fast faceting on the field.
=> Configuration update for Solr 4

warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
Fore reasons unknown, the canonicalization code from archive.org normalises `http://www.example.com/foo.bar` to `http://example.com/foo.bar` (it removes the `www.`-part), but normalises `http://www.example.com/` to `http://www.example.com/` (no change to the `www.`-part). Thanks for that, archive.org (I am sure they had good reasons, but it is quite vexing for me).
This pull request does an explicit check for `www.`-prefix and the other `w`-prefixes mentioned in #155.
With this, coupling `links` to `url_norm` should work for the vast majority of URLs.
=> URL normalisation/canonicalisation fixes

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/solr/TikaExtractor.java, warc-indexer/src/test/java/uk/bl/wa/solr/TikaExtractorTest.java
Whenever we log an error from WARC-indexing, we should also log where it occurred. This mostly means WARC filename and URL. This pull request adds the information to the error logging for TikaExtractor.
In principle the WARC is not needed, as one can step backwards in the logfile for the `info`-entry stating that parsing has started. However, such indirect information makes it hard to do automated processing of logs, such as grepping for recurring errors.
This is by no means a full review of error logging in the code. There are doubtless other parts of the code where we could do the same. The TikaExtractor is just the class where we see a lot of error messages.
=> Add source WARC & URL to most error logs for TikaExtractor

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/TikaPayloadAnalyser.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/main/java/uk/bl/wa/util/InputStreamUtils.java
@thomasegense made the code changes in this fix. I have only reviewed it and am doing the pull request logic. This pull requests closes #204 which means that WARCs from [Webrecorder](https://webrecorder.io/) should work with `webarchive-discovery`.
=> Webrecorder support

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/DroidDetectorAnalyser.java
The tool `wget` produces WARC-files with the values for the WARC-header `WARC-Target-URI` encapsulated in `<>`. Retrieving the URL from the WARC header in `warc-indexer` can be done safely using `Normalisation.sanitiseWARCHeaderValue` but this was not done for `DroidDetectorAnalyser`. This pull request fixes that.
This is an oversight that I am sure will come back to bite us, so I have raised issue #197.
=> Droid WARC URL header sanitize

warc-indexer/src/main/java/uk/bl/wa/analyser/WARCPayloadAnalysers.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/main/java/uk/bl/wa/util/CachedInputStreamFactory.java, warc-indexer/src/main/java/uk/bl/wa/util/HashedInputStream.java, warc-indexer/src/main/java/uk/bl/wa/util/InputStreamUtils.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerTest.java
This pull request addresses the problem with webrecorder chunked content, as described in [issue 218](https://github.com/ukwa/webarchive-discovery/issues/218), by checking to see if the beginning of the possibly chunked content fits the chunked content standard (hex digits).
=> Add heuristic check for chunked content

warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/util/HashedCachedInputStream.java, warc-indexer/src/main/java/uk/bl/wa/util/HashedInputStream.java, warc-indexer/src/main/java/uk/bl/wa/util/InputStreamUtils.java, warc-indexer/src/main/java/uk/bl/wa/util/Normalisation.java, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/test/java/uk/bl/wa/util/NormalisationTest.java
A WARC constructed by warcproxy (sorry, cannot be shared) demonstrated some bugs in the decompression and dechunking handling in `InputStreamUtils`, which this pull request fixes:
* An error was logged when 0-length content was marked as `gzip` (happens legally with revisits)
* Chunk-detection did not handle chunk markers with 8 hex-digits, only 1-7
* Chunk-detection did not handle uppercase hex digits
* Problems in chunk-detection did not log anything to identify the offending record (now it logs the URL)
The problems with dechunking were masked by the decompression step, as the errors logged were from the decompressor complaining about illegal input.
Furthermore this pull request fixes #233 #234  (partially) and #235 which are all problems with the hash values from digest intertwined …
=> Decompress and dechunk fixes

warc-indexer/src/main/java/uk/bl/wa/analyser/payload/TikaPayloadAnalyser.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerCommandTest.java
Apparently the Tika upgrade caused the keys for EXIF information in images to be changed. This again meant that geo coordinates were not extracted from images.
This pull-request adds checks for `GPS Latitude` (the old key), `GPS:GPS Latitude` (new key) and `geo:lat` (new key? With easier floating-point coordinate format). And of course the equivalent for longitude.
=> Fix code for getting geo coordinates from images

warc-indexer/src/main/java/uk/bl/wa/parsers/HtmlFeatureParser.java, warc-indexer/src/test/java/uk/bl/wa/analyser/payload/HTMLAnalyserTest.java, warc-indexer/src/test/resources/links_extract.html
This pull request adds support for [srcSet](https://webdesign.tutsplus.com/tutorials/quick-tip-how-to-use-html5-picture-for-responsive-images--cms-21015
) in `img` and `picture`, meaning that links from there will be added to the `links_images`-field in the SolrDocument.
This closes #246
=> Add support for indexing srcset links as image links

pom.xml
As described in #267, Maven 3.8.1 no longer accepts `http`-repos, but requires `https`. webarchive-discovery only uses `http` for the version99 repo, so fixing it is trivial (just insert a `s`).
=> Fix build for Maven 3.8.1

warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/resources/reference.conf, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerCommandTest.java
SolrWayback got the issue https://github.com/netarchivesuite/solrwayback/issues/192 about non-indexing of warcit WARCs. warcit WARCs are packed from the local filesystem and the individual records are of type `resource`. There were a few minor problems:
1. The default config did not include the `resource` type
2. Extraction of HTTP headers were attempted, but failed (naturally as there are none for local files). This meant that the HTTP status header was not set, so the record was discarded as invalid
3. There were no explicit mention of discarded records in the process log, so the summary at the end looked like everything went well
The 3 issues his are handled in this pull request.
=> Add support for resource WARC records (produced by e.g. warcit)

warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java
Currently the user needs to explicitly set the `-t` command line option to have warc-indexer produce freetext when using Elasticsearch. Since this is automatically enabled when using Solr, it makes sense to also auto-enable it for Elasticsearch.
A bit broader: Why is this an opt-in? Shouldn't text be the default, with the possibility of opting out?
=> Enable text output when using Elasticsearch, mirroring Solr behaviour

CHANGES.md, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexer.java, warc-indexer/src/main/java/uk/bl/wa/indexer/WARCIndexerCommand.java, warc-indexer/src/test/java/uk/bl/wa/indexer/WARCIndexerEmbeddedSolrTest.java
Now both source_file and source_file_path will be set as it was 3.2.
By mistake both values was put into source_file giving it the wrong value and leaving out source_file_path empty.
=> Reverting source_file_path back to value it was in 3.2.

warc-indexer/pom.xml, warc-indexer/src/main/java/uk/bl/wa/analyser/text/LanguageAnalyser.java
Changed LanguageAnalyser to use langid: 
[https://github.com/carrotsearch/langid-java/tree/master](https://github.com/carrotsearch/langid-java/tree/master)
It supports more languages and is more accurate. It is used in production at the National Library of Luxembourg because other analysers can't detect Luxembourgish.
=> Changed LanguageAnalyser to langid
